services:
  backend:
    build: ./backend
    env_file: ./backend/env/.env
    ports:
      - 8082:8082
    networks:
      - tg_bot_creator_nw
    depends_on:
      postgresql:
        condition: service_healthy
  #      redis:
  #        condition: service_healthy

  frontend:
    build: ./frontend
    env_file: ./frontend/.env
    ports:
      - 80:80
    networks:
      - tg_bot_creator_nw
    depends_on:
      - backend

  postgresql:
    image: postgres:16
    ports:
      - 5050:5432
    env_file: ./backend/env/.env
    volumes:
      - postgresql:/var/lib/postgresql/data
    networks:
      - tg_bot_creator_nw
    healthcheck:
      test: pg_isready -U postgres -d test_db
      interval: 20s
      timeout: 20s
      retries: 5

  migrate:
    image: migrate/migrate
    env_file: ./backend/env/.env
    volumes:
      - ./backend/migrations:/database
    networks:
      - tg_bot_creator_nw
    command:
      [
        '-path',
        '/database',
        '-database',
        'postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgresql:5432/${POSTGRES_DB_NAME}?sslmode=disable',
        'up',
      ]
    depends_on:
      postgresql:
        condition: service_healthy

volumes:
  postgresql: {}
#  minio_storage: {}
#  redis: {}

networks:
  tg_bot_creator_nw: {}
