DROP TABLE IF EXISTS order_items;

DROP TABLE IF EXISTS orders;

DROP TABLE IF EXISTS cart_items;

DROP TABLE IF EXISTS products;

DROP TABLE IF EXISTS tg_user_steps;

DROP TABLE IF EXISTS buttons;

DROP TABLE IF EXISTS steps;

DROP TABLE IF EXISTS bots;

DROP TABLE IF EXISTS users;
